POST http://localhost:3000/v1/contract
Content-Type: application/json

{
  "incoterm": "exw",
  "signDate":{
    "text1": "18th September 2025"
  },
  "contractNo":"25KCT23",
  "contractDetails": [
    {
       "key":"Project",
       "value":"Q-2025-059 Comstock Pond Cover"
    },
    {
       "key":"Item",
       "value":"STEEL STRUCTURE"
    },
    {
       "key":"Location",
       "value":"CANADA"
    }
  ]
}
